booksite/books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.books_home, name='books_home'),
    path("<int:pk>", views.BooksDetailView.as_view(), name='books-detail'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart '),
    path('update_cart/<int:item_id>/', views.update_cart, name='update_cart'),
]

booksite/booksite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('money.urls')),
    path('books/', include('books.urls')),


    path('registration/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

booksite/money/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
]

booksite/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home_regist'),
    path('registration/', views.register, name='register')
]

booksite/books/models.py
from django.db import models
from django.contrib.auth.models import User


class Bookks(models.Model):
    GENRE_CHOICES = [
        ('fiction', 'Художня література'),
        ('sci-fi', 'Наукова фантастика'),
        ('fantasy', 'Фентезі'),
        ('detective', 'Детектив'),
    ]

    title = models.CharField('Назва', max_length=50)
    genre = models.CharField('Жанр', max_length=50, choices=GENRE_CHOICES)
    author = models.CharField('Автор', max_length=50)
    priсe = models.DecimalField('Ціна', max_digits=10, decimal_places=2)
    full_text = models.TextField('Опис')
    date = models.DateTimeField('Дата публікації')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Книжка'
        verbose_name_plural = 'Книжки'


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Bookks, through='CartItem')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart for {self.user.username}"



class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    book = models.ForeignKey(Bookks, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.book.priсe * self.quantity

booksite/money/models.py
from django.db import models

# Create your models here.

booksite/users/models.py
from django.db import models

# Create your models here.

booksite/money/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

booksite/users/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

booksite/books/views.py
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .models import Cart, Bookks, CartItem
from django.db.models import Q


def books_home(request):
    genre = request.GET.get('genre')
    search_query = request.GET.get('search')
    books = Bookks.objects.order_by('-date')
    if genre:
        books = books.filter(genre=genre)
    if search_query:
        books = books.filter(Q(title__icontains=search_query) | Q(author__icontains=search_query))
    return render(request, 'books/books_home.html', {'books': books})


class BooksDetailView(DetailView):
    model = Bookks
    template_name = 'books/books_view.html'
    context_object_name = 'books'


@login_required
def cart(request):
    cart_items = CartItem.objects.filter(cart__user=request.user)
    total = sum(item.subtotal() for item in cart_items)
    return render(request, 'books/cart.html', {'cart_items': cart_items, 'total': total})


def add_to_cart(request, pk):
    book = get_object_or_404(Bookks, id=pk)
    cart, created = Cart.objects.get_or_create(user=request.user.pk)
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, book=book)
    if not item_created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart')


def remove_from_cart(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk)
    cart_item.delete()
    return redirect('cart')


def update_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, pk=item_id)
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 0))
        if quantity > 0:
            cart_item.quantity = quantity
            cart_item.save()
        else:
            cart_item.delete()
    return redirect('cart')

booksite/money/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm

def index(request):
    data = {
        'title': 'Головна сторінка',
    }
    return render(request, 'money/index.html', data)

def about(request):
    return render(request, 'money/about.html')

booksite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import UserRegistrationForm
from books.models import Cart

def home(request):
    return render(request, 'users/home_regist.html')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Створюємо об'єкт Cart для нового користувача
            cart = Cart.objects.create(user=user)

            messages.success(request, f'Your account has been created. You can log in now!')
            return redirect('login')
    else:
        form = UserRegistrationForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)


booksite/books/templates/books/books_home.html
{% extends 'money/layout.html' %}

{% block title %}Католог книжок{% endblock %}

{% block content %}
<style>
    hr {
        margin-left: 20%;
        color: rgba(220, 20, 60, 0.96);
        border-width: 5px;
    }

    h1 {
        margin-left: 23%;
        margin-top: 15px;
        color: crimson;
    }

</style>
<h1>Католог книжок</h1>
<hr>
<form method="GET" action="{% url 'books_home' %}">
    <div class="form-row" style="margin-left: -15%; margin-top: -25px; margin-bottom: 10px">
        {% include 'books/table_sort.html' %}
    </div>
</form>
<div class="features">
    {% if books %}
    <div class="row">
        {% for book in books %}
        <div class="col-md-4">
            {% include 'books/table_home.html' %}
        </div>
        {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <p>No books found.</p>
    {% endif %}
</div>

{% endblock %}

booksite/books/templates/books/books_view.html
{% extends 'money/layout.html' %}

{% block title %}{{ books.title }}{% endblock %}

{% block content %}
<style>
    table {
        border-collapse: collapse;
        border: 1px solid #ddd;
        border-radius: 10px;
        min-height: 300px;
        margin-top: 50px;
    }

    td,
    th {
        border: 0;
    }

    .book-image {
        max-width: 200px;
        max-height: 300px;
    }

</style>

<div class="content">
    <table>
        <tr>
            <td rowspan="2" style="background: black; color: #ffffff;  vertical-align: top; width: 200px">
                <h2>{{ books.title }}</h2>
            </td>
            <td style="background: white; vertical-align: top; height: 6px">{{ books.date }}<br>{{ books.author }}</td>
        </tr>
        <tr>
            <td rowspan="2" style="background: white; vertical-align: top;">{{ books.full_text }}</td>
        </tr>
        <tr>
            <td style="background: black;  vertical-align: bottom; color: rgb(134,134,134); height: 100px">
                Ціна: {{ books.priсe }} ₴ <br>
                Код товару: {{ books.id }}
                {% include 'books/btn_add.html' %}
            </td>
        </tr>
    </table>
</div>

{% endblock %}

booksite/books/templates/books/btn_add.html
<style>
    .btn-add-styled {
        width: 100%;
        height: 42px;
        line-height: 2.5;
        padding: 0 20px;
        font-size: 1rem;
        text-align: center;
        white-space: nowrap;
        color: #fff;
        border-radius: 0;
        background-color: #4d4d4d;
    }

    .btn-add-styled:hover {
        background-color: rgba(77, 77, 77, 0.51);
    }
</style>


<div>
    {% if user.is_authenticated %}
        <a class="btn btn-add-styled" href="{% url 'add_to_cart' books.id %}">Додати до кошика</a>
    {% else %}
        <a class="btn btn-add-styled" href="{% url 'home_regist' %}">Ви не увійшли у систему</a>
    {% endif %}
</div>

booksite/books/templates/books/btn_pay.html
<style>
    .btn-add-styled {
        width: 100%;
        height: 42px;
        line-height: 2.5;
        padding: 0 20px;
        font-size: 1rem;
        text-align: center;
        white-space: nowrap;
        color: #fff;
        border-radius: 10px;
        background-color: #4d4d4d;
    }

    .btn-add-styled:hover {
        background-color: rgba(77, 77, 77, 0.51);
    }
</style>


<div>
    <a class="btn btn-add-styled" href="">Оплатити</a>
</div>

booksite/books/templates/books/cart.html
{% extends 'money/layout.html' %}

{% block content %}

<div>
    <style>
        table {
            background: white;
            margin-left: 23%;
            border-collapse: collapse;
            border: 2px solid aqua;
        }

        h1 {
            margin-left: 23%;
            margin-top: 15px;
            color: crimson;
        }


        hr {
            margin-left: 20%;
            color: rgba(220, 20, 60, 0.96);
            border-width: 5px;
        }

    </style>
    <h1>Кошик</h1>

    <table>
        <hr>
        <thead>
        <tr>
            <th style="min-width: 150px; max-width: 250px; height: 50px;">Назва</th>
            <th style="width: 100px; height: 50px;">Кількість</th>
            <th style="width: 150px; height: 50px;">Ціна за штуку</th>
            <th style="width: 100px; height: 50px;">Підсумок</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart_items %}
        <tr>
            <td>{{ item.book.title }}</td>

            <td>
                <form method="POST" style="margin: 0; width: 125px" action="{% url 'update_cart' item.id %}">
                    {% csrf_token %}
                    <input type="number" style="width: 75px" name="quantity" value="{{ item.quantity }}" min="0">
                    <button type="submit">↻</button>
                </form>
            </td>

            <td>{{ item.book.priсe }}</td>
            <td>{{ item.subtotal }}</td>
        </tr>
        {% endfor %}

        <tr>
            <td colspan="2"></td>
            <td style="height: 55px"><strong>Загальна сума:</strong></td>
            <td>{{ total }}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2">
                {% include 'books/btn_pay.html' %}
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

booksite/books/templates/books/table_home.html
<style>
    .book-card {
        margin-bottom: 20px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        height: 200px;
        width: 350px;
        margin-top: 10px;
        margin-left: 15px;
    }
</style>

<div class="book-card">
    <table>
        <tr>
            <td style="height: 55px; vertical-align: top">
                <h5>{{ book.title }}</h5>
            </td>
        </tr>
        <tr>
            <td style="height: 70px; vertical-align: top">
                <p>Автор: {{ book.author }}</p>
                <p>Жанр: {{ book.get_genre_display }}</p>
            </td>
        </tr>
        <tr>
            <td>
                <a href="{% url 'books-detail' book.pk %}" class="btn btn-warning"
                   style="vertical-align: bottom">Детальніше
                </a>
            </td>
        </tr>
    </table>
</div>

booksite/books/templates/books/table_sort.html
<table>
    <thead>
    <tr>
        <th><label for="genreSelect" style="color: crimson">Жанр:</label></th>
        <th><label for="searchInput" style="color: crimson">Пошук:</label></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <div class="form-group col-md-4" style="width: 80%">
                <select class="form-control" id="genreSelect" name="genre">
                    <option value="">Всі</option>
                    <option value="fiction">Художня</option>
                    <option value="nonfiction">Наукова</option>
                    <option value="sci-fi">Наукова фантастика</option>
                    <option value="fantasy">Фентезі</option>
                </select>
            </div>
        </td>
        <td>
            <div class="form-group col-md-6" style="width: 80%">
                <input type="text" class="form-control" id="searchInput" name="search"
                       placeholder="Назва або автор">
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <button type="submit" style="margin: 0 auto" class="btn btn-primary">Фільтрувати</button>
        </td>
    </tr>
    </tbody>

</table>


booksite/money/templates/money/about.html
{% extends 'money/layout.html' %}

{% block title %}Контакти{% endblock %}

{% block content %}
<style>
    h1 {
        margin-left: 23%;
        margin-top: 15px;
        color: crimson;
    }

    p {
        margin-left: 15px;
        margin-top: 15px;
        font-size: 18px;
    }

    hr {
        margin-left: 20%;
        color: rgba(220, 20, 60, 0.96);
        border-width: 5px;
    }

    .contact-info {
        margin-left: 23%;
        margin-top: 15px;
        color: white;
    }
</style>

<h1>Контакти</h1>
<hr>

<div class="contact-info">
    <h3>Служба підтримки</h3>
    <p>Якщо у вас виникли питання або потрібна допомога, будь ласка, зв'яжіться з нашою службою підтримки:</p>
    <p>Електронна пошта: <a href="mailto:support@example.com">support@gmail.com</a></p>
</div>
<br><br>
<div class="contact-info">
    <h3>Телеграм</h3>
    <p>Ви також можете зв'язатися з нами через Телеграм:</p>
    <p>Наш канал: <a href="https://t.me/example_channel">t.me/support_channel</a></p>
</div>

{% endblock %}

booksite/money/templates/money/index.html
{% extends 'money/layout.html' %}

{% block title %}Головна сторінка{% endblock %}

{% block content %}
<style>
    h1 {
        margin-left: 23%;
        margin-top: 15px;
        color: crimson;
    }

    p {
        font-size: 18px;
        color: #ffffff;
    }

    hr {
        margin-left: 20%;
        color: rgba(220, 20, 60, 0.96);
        border-width: 5px;
    }

    .cta-button {
        margin-left: 23%;
        margin-top: 15px;
    }

    div p {
        margin-left: 23%;
        margin-top: 15px;
        width: 1100px;
    }
</style>

<h1>Ласкаво просимо до нашого магазину книжок!</h1>
<hr>

<div>
    <p>У нашому магазині ви знайдете великий вибір книжок різних жанрів: художня література, наукова фантастика, фентезі
        та детективи.</p>

    <p>Ми пропонуємо як класичні твори, так і новинки від українських та світових авторів. Ви зможете насолодитися
        захоплюючими історіями та поглибити свої знання в різних сферах.</p>

    <p>Наші книжки відрізняються високою якістю та доступними цінами. Ми прагнемо надати найкращі можливості для вашого
        читання та задоволення.</p>

    <a href="{% url 'books_home' %}" class="btn btn-primary cta-button">Переглянути каталог</a>
</div>

{% endblock %}

booksite/money/templates/money/layout.html
{% load static %}
<!doctype html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'money/css/money.css' %}">

</head>
<body>
    <aside>
        <picture>
            <img src="{% static 'money/img/symbol.jpg' %}" alt="logo">
        </picture>
        <style>
            a {
                text-decoration: none;
            }
        </style>
        <h3>Навігація 🧭</h3>
        <ul>
            <a href="{% url 'home' %}"><li>Головна</li></a>
            <a href="{% url 'books_home' %}"><li>Книжки</li></a>
            <a href="{% url 'home_regist' %}"><li>Профіль</li></a>
            <a href="{% url 'about' %}"><li>Контакти</li></a>
        </ul>
        {% include 'users/btn_regist.html' %}

    </aside>

    <main>
        {% block content %}
	    {% endblock %}
    </main>
</body>
</html>

booksite/users/templates/users/btn_regist.html
<style>
    .btn-styled {
        width: 100%;
        height: 55px;
        line-height: 2.5;
        padding: 0 20px;
        font-size: 1rem;
        text-align: center;
        white-space: nowrap;
        color: #fff;
        border-radius: 10px;
        background-color: #4d4d4d;
    }

    .btn-styled:hover {
        background-color: rgba(77, 77, 77, 0.51);
    }
</style>

{% if user.is_authenticated %}
<div>
    <a href="{% url 'cart' %}" style="font-size: 22px; overflow: hidden;text-overflow: ellipsis;"
       class="btn btn-styled">
        🛒: {{ user.username }}
    </a>
</div>
{% else %}
<div>
    <a href="{% url 'home_regist' %}" style="font-size: 22px" class="btn btn-styled">
        Login / Signin
    </a>
</div>
{% endif %}

booksite/users/templates/users/home_regist.html
{% extends 'money/layout.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <div class="alert successful">
        <h1>Вітаю {{ user.username }}!</h1>
        <a href="{% url 'logout' %}" style="font-size: 22px;">Вийти?</a>
    </div>
    {% else %}
    <div class="alert successful">
        <h1>Вітаю!</h1>
        <a href="{% url 'register' %}" style="font-size: 22px;">Зареєструватися</a><br>
        <a href="{% url 'login' %}" style="font-size: 22px;">Увійти</a>
    </div>
    {% endif %}
{% endblock %}


booksite/users/templates/users/login.html
{% extends 'money/layout.html' %}

{% block content %}
<div class="alert successful">
    <h1>Увійти</h1>
    <style>
        form {
            margin: 0;
        }
    </style>
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <p>{{ field.label }}: <br> {{ field }}</p>
        {% endfor %}
        <button type="submit">Увійти</button>
    </form>
    <hr>

    <p>Ще не зареєструвалися? <a href="{% url 'register' %}">Зробіть це тут</a></p>
</div>
{% endblock %}

booksite/users/templates/users/logout.html
{% extends 'money/layout.html' %}

{% block content %}
<br>
<div class="alert successful">
    <h1 style="text-align: center;">Ви вийшли з системи</h1><br>
    <h3>Увійти знову?</h3>
    <a href="{% url 'login' %}">---> Увійти</a> <br>
    <a href="{% url 'home' %}"><--- Або повернутися на головну сторінку.</a>
</div>


{% endblock content %}

booksite/users/templates/users/register.html
{% extends 'money/layout.html' %}

{% block content %}
<div class="alert successful">
    <h3>Реєстрація</h3>
    <br>
    <style>
        form {
            margin: 0;
        }
    </style>
    <form action="" method="POST">
        {% csrf_token %}

        {% for field in form %}
        <div>
            <p>{{ field.label }}: <br> {{ field }}</p>

            {% for error in field.errors %}
            <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
        {% endfor %}
        <br>
        <button type="submit">Зареєструвати</button>
    </form>
</div>
{% endblock %}